import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Provider from "./provider";

const inter = Inter({ subsets: ["latin"] });

export const Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<Provider>
			<html lang="en">
				<body className={inter.className}>{children}</body>
			</html>
		</Provider>
	);
}
